# name: helm-upgrade


# run-name: ${{ github.actor }} - ${{ github.ref_name }}


# on:
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         description: 'Environment to deploy to'
#         type: string
#       helm-values-path:
#         description: 'Path to the helm values file'
#         type: string
#         default: './kube2py/values.yaml'
#       helm-release-name:
#         description: 'Name of the helm release'
#         type: string
#         default: kube2py
# jobs:
#   deploy-helm:
#     runs-on: ubuntu-latest
#     environment: ${{ inputs.environment }}
#     name: ${{ inputs.environment }}


#     steps:
#     - uses: actions/download-artifact@v4
#       with:
#         name: helm-package
#         path: .


#     - uses: actions/download-artifact@v4
#       with:
#         name: helm-artifacts
#         path: .


#     - name: Set up Helm
#       uses: azure/setup-helm@v4.2.0


#     - uses: azure/setup-kubectl@v4
#       name: Set up Kubectl


#     - uses: azure/login@v2
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}


#     - uses: azure/aks-set-context@v3
#       with:
#         cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}
#         resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}

#     - name: Deploy to Dry Run
#       run: |
#         helm install --dry-run ${{ inputs.helm-release-name }} ./kube2py-*.tgz  \
#           -f ${{ inputs.helm-values-path }} \
#           --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.KUBE2PY_MYSQL_ROOT_PASSWORD }}" \
#           --set mysql.configs.MYSQL_USER="${{ secrets.KUBE2PY_MYSQL_USER }}" \
#           --set mysql.configs.MYSQL_PASSWORD="${{ secrets.KUBE2PY_MYSQL_PASSWORD }}" \
#           --set kube2py.secrets.password="${{ secrets.KUBE2PY_PASSWORD }}" \
#           --set kube2py.secrets.login="${{ secrets.KUBE2PY_LOGIN }}" \
#           --set kube2py.secrets.DB_CONNECTION="${{ secrets.KUBE2PY_DB_CONNECTION }}" \
#           --set kube2py.image.version="${{ github.sha }}" \
#           --set common.namespace="mateapp-${{ inputs.environment }}" \
#           --set mysql.namespace="mysql-${{ inputs.environment }}"

#     - name: Deploy Helm
#       run: |
#         helm upgrade --install --atomic  --wait --timeout 1800s --debug ${{ inputs.helm-release-name }} ./kube2py-*.tgz  \
#           -f ${{ inputs.helm-values-path }} \
#           --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.KUBE2PY_MYSQL_ROOT_PASSWORD }}" \
#           --set mysql.configs.MYSQL_USER="${{ secrets.KUBE2PY_MYSQL_USER }}" \
#           --set mysql.configs.MYSQL_PASSWORD="${{ secrets.KUBE2PY_MYSQL_PASSWORD }}" \
#           --set kube2py.secrets.password="${{ secrets.KUBE2PY_PASSWORD }}" \
#           --set kube2py.secrets.login="${{ secrets.KUBE2PY_LOGIN }}" \
#           --set kube2py.secrets.DB_CONNECTION="${{ secrets.KUBE2PY_DB_CONNECTION }}" \
#           --set kube2py.image.version="${{ github.sha }}" \
#           --set common.namespace="mateapp-${{ inputs.environment }}" \
#           --set mysql.namespace="mysql-${{ inputs.environment }}"
