name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Envitoment to deploy to"
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './kube2py/values.yaml'
      helm-release-name:
        default: kube2py
        type: string

jobs:

  helm-deploy:

    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: helm-artifact
        path: .

    - uses: actions/download-artifact@v4
      with:
        name: helm-package
        path: .

    - name: Setup Helm
      uses: azure/setup-helm@v4.3.0

    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - uses: azure/login@v2
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v4
      with:
         resource-group: '${{ vars.AZURE_RESOURCE_GROUP }}'
         cluster-name: '${{ vars.AZURE_CLUSTER_NAME }}'

    - name: Deploy Helm to ${{ inputs.environment }}
      run: |
        helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./kube2py-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set kybe2py.secrets.password="${{ secrets.KUBE2PY_PASSWORD }}" \
          --set kybe2py.secrets.login="${{ secrets.KUBE2PY_LOGIN }}" \
          --set kybe2py.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
          --set kybe2py.image.version=${{ github.sha }}






