name: CI
run-name: ${{ github.actor }} was run current workflow.
env:
  GITHUB_ACTIONS: CurrentActions
on:
  pull_request:
    branches: [ "main" ]
jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_ACTIONS is ${{ env.GITHUB_ACTIONS }}"
      - run: echo "Branch name is ${{ github.ref }}, repo name is ${{ github.repository }}"
      - run: echo "Current job was triggered by event ${{ github.event_name }}"
