
global:
  ENVIRONMENT: placeholder
  namespace: kube2py-staging

commmon:
  namespace: kube2py-staging

mysql:
  namespace: mysql-staging

kube2py:
  configs:
    APP_ENV: "testing-helm-staging"
  image:
    repository: fredisson11/kube2py
    version: placeholder

  secrets:
    password: placeholder # MyStrongerPassword
    login: placeholder # SuperSuperUser

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "100m"

  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 5